### ISSUE TITLE
Output confidence intervals

### ISSUE THREAD

**Issue by woook** [moka-guys/dnanexus_happy#4]
R code:

```
install.packages("epiR")
library("epiR")

#Provide numbers in order TP,FP,FN,TN   
dat <- as.table(matrix(c(11068,36,105,14141122), nrow = 2, byrow = TRUE))
rval <- epi.tests(dat, conf.level = 0.95)
print(rval); summary(rval)
```

**Comment by andyb3** [comment]
Above requires True Negatives which we don't have. Seems like a binomial proportion confidence interval is required (https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval). Wilson or Jeffreys are the preferred methods (http://epitools.ausvet.com.au/content.php?page=CIProportion)

GIAB suggest using binconf in R (see point 8e here: https://github.com/genome-in-a-bottle/giab_FAQ) which uses Wilson by default, don't think it can do Jeffreys. Illumina use Jeffreys method in som.py tool,
not sure why they output CI for som.py but not hap.py (https://github.com/Illumina/hap.py/blob/master/doc/sompy.md).  

The binom R package which can do Wilson or Jeffreys. (https://cran.r-project.org/web/packages/binom/binom.pdf

**Comment by andyb3** [comment]
Here is the code used to calculate Jeffreys CI in hap.py repository: https://github.com/Illumina/hap.py/blob/master/src/python/Tools/ci.py

**Comment by andyb3** [comment]
Add `--ci-alpha 0.05` to hap.py command to output 95% CI limits to extended.csv. (See https://github.com/Illumina/hap.py/issues/26).
